### ISSUE TITLE
How to access the router instance from a stateless function component?

### ISSUE THREAD

**Issue by martindederer** [zxbodya/router1-app-template#1]
You are using stateless function components in the router1-app-template example project. How do you access the router instance from such a component? RouterContext adds the router instance to the child context but not the child properties. Stateless function components can not access the context. Is there a designated method to pass in the router as an additional property to the wrapped (by createContainer) component when i want to use stateless function components for my views?

If i remember correctly react-router has convenience methods for navigating back to the last view. Does router1 have a counterpart? Is it actually necessary to access the router instance in order to facilitate generic "back navigation" or is there a more idiomatic way?

**Comment by martindederer** [comment]
I might be suffering from the xy problem. What i want to achieve is generic back navigation and accessing the route parameters from a stateless function component.

**Comment by zxbodya** [comment]
Hi, 

Typically I do not access it directly… - there is `Link` and `ActiveWrap` components in `router1-react` package, and it is enough for most use-cases I have.

If you need do to something custom in a view component with router - you can use it via context (btw, it is supported by stateless functional components too - for example see Link component implementation https://github.com/zxbodya/router1-react/blob/master/src/Link.js)

About methods for navigating back/forward: right now, there is no methods for that, I suggest that it should not be part of router, it is rather about history abstraction used by router, or rather underling browser API…  

Not sure about adding back/forward - it might be useful… but not sure does it worth to be added

And you can do it without interacting with router - just use DOM api - `history.back()/history.forward()/history.go()`, and router will handle that just ok.

--- 

About getting router instance outside of the views - simplest way is to just import router instance…

**Comment by zxbodya** [comment]
> What i want to achieve is generic back navigation and accessing the route parameters from a stateless function component.

With current implementation of router1-app-template, it would be something like this:

```JS
export default function (params) {
  return {
    meta: {
      title: 'Home page',
      description: 'home page description',
    },
    view: createContainer(Home, {}, {}, {
      params,
      back() {
        window.history.back()
      }
    }),
  };
}
```

**Comment by martindederer** [comment]
Thanks for the hint about the availability of the context in stateless function components. I missed that somehow.

I agree with you in regard to the navigation shortcuts. The router should not know about that stuff.

**Comment by martindederer** [comment]
Do you have have an example that shows how to work with route parameters?

My route data structure looks like this:

```javascript
const routes = [
  {
    name: 'home',
    url: '/',
    handler: HomeHandler
  },
...
  {
    name: 'entity',
    url: '/entity/<id:\d+>',
    handler: EntityHandler
  }
]
```

The link to the route looks like this:

```javascript
<Link route='entity' params={{ id: "4" }}>Entity 4</Link>
```

However the entity route does not match and therefore the handler does not receive any params. Is this how you intended to use it?

**Comment by martindederer** [comment]
It works when i use

```javascript
const routes = [
...
  {
    name: 'entity',
    url: '/entity/<id>',
    handler: EntityHandler
  }
]
```

Weird. The id i use is definitely a valid decimal. When i use

```javascript
url: '/entity/<id:.+>'
```

i get a route match too.

**Comment by zxbodya** [comment]
That is because of invalid `url`:

You need to escape `\` character in string literals, otherwise it would be just escaped `d` which eventually would be just `d` in resulting string

It should be `url: '/entity/<id:\\d+>',`

**Comment by martindederer** [comment]
Yes, that's it. This typo is also in the router1/readme.md file.

Thanks. :smile:

**Comment by zxbodya** [comment]
good catch, will update readme soon.

**Comment by zxbodya** [comment]
updated router1 documentation.

made some nice updates to this app template in order to make it cleaner and easier to use

btw, updated template and all my modules to use RxJS 5 (`router1`, `rx-react-container`).. so If using RxJS 4, there is branch named `rxjs4`

**Comment by martindederer** [comment]
Thanks for updating to rxjs version 5. This was kind of bothering me and i had to downgrade all other dependencies to version 4. Problem solved. Kudos to you. :)
